name: Deploy to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and tag Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hound-client:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hound-client:latest

    - name: Update image metadata
      uses: docker/metadata-action@v3
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/hound-client:latest
        tags: |
          ${{ github.sha }}

    - name: Set environment variables
      run: |
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV